### ISSUE TITLE
Check why the information value tests consume so much memory

### ISSUE THREAD

**Issue by finiteautomata** [finiteautomata/leninanalysis#1]
Running the tests of moby dick consumes so much memory with as many as 5 threads.

Try `python cccp.py --test` on my branch and memory consumed scales up to 2 gb.

**Comment by llazzaro** [comment]
https://github.com/geekazoid/leninanalysis/commit/2b41ea78faf8ce9a1d7079667ee257ddbf5cafa7

**Comment by llazzaro** [comment]
https://github.com/geekazoid/leninanalysis/commit/eb81b011c936c7eb0adc2e2f212fd0e1fbc3eba9

**Comment by llazzaro** [comment]
avoid token duplication on window creation https://github.com/geekazoid/leninanalysis/commit/c80deac2114547a96011f0b67b25eab77f81cee2

https://github.com/geekazoid/leninanalysis/commit/5ef934e9028d7a7ddbb706e8d16de326ba7ddd9a

**Comment by llazzaro** [comment]
https://github.com/geekazoid/leninanalysis/commit/84429536126de4085297a5248b201e0bfbf196c7

**Comment by llazzaro** [comment]
more improvements https://github.com/geekazoid/leninanalysis/commit/6d8f1a30dedd823bda68100ab6614ace96cebea5

https://github.com/geekazoid/leninanalysis/commit/e70bf7072bce957be722e62f4ad773b006db24f0

**Comment by llazzaro** [comment]
https://github.com/geekazoid/leninanalysis/commit/3e3cf5d918291cb913762cf84ee7ec9a3543ff05
