### ISSUE TITLE
Save IV results in mongodb

### ISSUE THREAD

**Issue by finiteautomata** [finiteautomata/leninanalysis#5]
for each text and for all windows sizes save all iv results

Analisis

Document

{
url: 
text
name
month
year:
"results: [(threshold, windows_sizes)]" # the best window_size for the threshold
}

AnalisysResult
{
window_size,
document_id,
iv_results: {iv_words, }
}

It should also save the sum threshold.
it should answer: which is the best window for one threshold?

**Comment by llazzaro** [comment]
initial model pushed.
https://github.com/geekazoid/leninanalysis/commit/47893b1941aea69aac57e1893b9d3c9cae72f866

next step is to use it in the scraper and for saving results.

**Comment by llazzaro** [comment]
https://github.com/geekazoid/leninanalysis/commit/26623b9a01cb581139d32b8084d4978b0bcae520
