### ISSUE TITLE
Add travis to project

### ISSUE THREAD

**Issue by llazzaro** [finiteautomata/leninanalysis#7]
I already added the config file (https://github.com/geekazoid/leninanalysis/commit/d54cf606ea427dce722266d82f795ddfb13008dd)

project owner should create an account at https://travis-ci.org/ and then add the project on https://travis-ci.org/profile

This will build the project

**Comment by finiteautomata** [comment]
travis? really? :-p

Ahora que lo pienso, meterle CI para los tests largos estaría re piola....

Saludos,

JM

**Comment by llazzaro** [comment]
Solo el owner del projecto puede agregarle el travis. es medio al pedo pero queda lindo ver un projecto en github con la imagen de build success :P
